listings/urls.py
from django.urls import path
from .import views


app_name ='listings'
urlpatterns =[
    
    # email_us 
    path('Email_us/',views.Email_us, name='Email_us'),
    
    # index
    path('', views.index, name='index'),
    
    # grade 
    path('grade_signup/',views.grade_signup, name='grade_signup'),
    path('grade_list/', views.grade_list, name='grade_list'),
    path('grade_list/detail/<slug:grade_slug>/',views.grade_detail, name='grade_detail'),
    path('grade_list/edit/<slug:grade_slug>/',views.grade_edit, name='grade_edit'),
    path('grade_list/delete_ask/<slug:grade_slug>/',views.grade_delete_ask, name='grade_delete_ask'),
    path('grade_list/delete/<slug:grade_slug>/',views.grade_delete, name='grade_delete'),
    # grade attendance students
    path('grade_attendance/<slug:grade_slug>/create/',views.grade_attendanc_create, name='grade_attendanc_create'),
    path('grades_dashboard/', views.grade_dashboard, name='grade_dashboard'),
    path('grade_attendance/<slug:grade_slug>/list/',views.attendance_list, name='attendance_list'),
    # path('grade_attendance/<slug:grade_slug>/',views.grade_attendanc, name='grade_attendanc'),
   
   # subject 
    path('subject_signup/',views.subject_signup, name='subject_signup'),
    path('subject_list/',views.subject_list, name='subject_list'),
    path('subject_list/detail/<slug:subject_slug>/',views.subject_detail, name='subject_detail'),
    path('subject_list/edit/<slug:subject_slug>/',views.subject_edit, name='subject_edit'),
    path('subject_list/delete_ask/<slug:subject_slug>/',views.subject_delete_ask, name='subject_delete_ask'),
    path('subject_list/delete/<slug:subject_slug>/',views.subject_delete, name='subject_delete'),
    path('subject_grade_dashboard/', views.subject_grade_dashboard, name='subject_grade_dashboard'),
    path('subject_mark_student_list/<slug:grade_slug>/<slug:subject_slug>/', views.subject_mark_student_list,
         name='subject_mark_student_list'),
    path('subject_mark_student_detail/<slug:grade_slug>/<slug:subject_slug>/<str:student_username>/', views.subject_mark_student_detail,
         name='subject_mark_student_detail'),

    # mark
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/mark_add/',views.mark_create, name='mark_create'),
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/<int:mark_id>/mark_edit/',views.mark_edit, name='mark_edit'),
    # path('mark/<str:student_username>/create/',views.mark_student_create, name="mark_student_create"),

    # user
    path('user_list/', views.user_list,name='user_list'),
    
    # school admin
    path('schadmin_list/',views.schadmin_list,name='schadmin_list'),
    path('schadmin_list/detail/<str:schadmin_username>/',views.schadmin_detail, name='schadmin_detail'),
    
    # teacher
    path('teacher_list/',views.teacher_list,name='teacher_list'),
    path('teacher_list/detail/<str:teacher_username>/',views.teacher_detail, name='teacher_detail'),
  
    # student
    path('student_list/',views.student_list,name='student_list'),
    path('student_list/detail/<str:student_username>/',views.student_detail, name='student_detail'),
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/mark/',views.student_subject_mark_detail, name='student_subject_mark_detail'),
   
    path('student_list/detail/<str:student_username>/marks',views.student_detail_marks, name='student_detail_marks'),
    path('student_list/detail/<str:student_username>/attendance',views.student_detail_attendance, name='student_detail_attendance'),
    path('student_list/detail/<str:student_username>/messages',
         views.student_detail_messages, name='student_detail_messages'),
    
    # parent
    path('parent_list/', views.parent_list, name='parent_list'),
    path('parent_list/detail/<str:parent_username>/',views.parent_detail, name='parent_detail'),
    
    # charts
    path('charts_all/', views.charts_all, name='charts_all'),
 
]

sch_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('listings.urls', namespace='listings')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from.import views


app_name = 'users'
urlpatterns = [
    # login
    path('login/', views.login_user, name='login_user'),
    # logout
    path('logout/', views.logout_user, name='logout_user'),
    # profile
    path('profile/',views.profile,name='profile'),
    # image update
    path('image_update/<str:user_username>/',views.image_user_update, name='image_user_update'),
    
    # main dashboard
    path('main_dashboard/', views.main_dashboard, name='main_dashboard'),

    # webadmin 
    path('webadmin_profile/', views.webadmin_profile, name='webadmin_profile'),
    path('webadmin_dashboard/<str:webadmin_username>/',views.webadmin_dashboard, name='webadmin_dashboard'),

    # Academic Year
    path('academicyear_add/', views.academicyear_add, name='academicyear_add'),
    path('academicyear_edit/<str:year_name>/',views.academicyear_edit, name='academicyear_edit'),
    path('academicyear_delete/<str:year_name>/',views.academicyear_delete, name='academicyear_delete'),
   

    # schooladmin
    path('schadmin_profile/', views.schadmin_profile, name='schadmin_profile'),
    path('schadmin_dashboard/<str:schadmin_username>/',views.schadmin_dashboard, name='schadmin_dashboard'),
    path('schooladmin_signup/', views.schadmin_signup, name='schadmin_signup'),
    path('schooladmin_list/<str:schadmin_username>/edit',views.schadmin_edit, name='schadmin_edit'),
    path('schooladmin_list/<str:schadmin_username>/delete_ask/',views.schadmin_delete_ask, name='schadmin_delete_ask'),
    path('schooladmin_list/<str:schadmin_username>/delete',views.schadmin_delete, name='schadmin_delete'),

    # teacher
    path('teacher_profile/', views.teacher_profile, name='teacher_profile'),
    path('teacher_dashboard/<str:teacher_username>/', views.teacher_dashboard,name='teacher_dashboard'),
    path('teacher_signup/', views.teacher_signup, name='teacher_signup'),
    path('teacher_list/<str:teacher_username>/edit',views.teacher_edit, name='teacher_edit'),
    path('teacher_list/<str:teacher_username>/delete_ask',views.teacher_delete_ask, name='teacher_delete_ask'),
    path('teacher_list/<str:teacher_username>/delete',views.teacher_delete, name='teacher_delete'),
    path('teacher_smessage/<str:student_username>/',views.message_t_student_send, name='message_t_student'),
    path('teacher_gmessage/<slug:grade_slug>/',views.message_t_grade_send, name='message_t_grade'),
    
    # student
    path('student_profile/', views.student_profile, name='student_profile'),
    path('student_dashboard/<str:student_username>/',views.student_dashboard, name='student_dashboard'),
    path('student_signup/', views.student_signup, name='student_signup'),
    path('student_list/<str:student_username>/edit',views.student_edit, name='student_edit'),
    path('student_list/<str:student_username>/delete_ask',views.student_delete_ask, name='student_delete_ask'),
    path('student_list/<str:student_username>/delete',views.student_delete, name='student_delete'),
    
    
    # parent
    path('parent_profile/', views.parent_profile, name='parent_profile'),
    
    path('parent_student_dashboard/<str:student_username>/',
         views.parent_student_dashboard, name='parent_student_dashboard'),
    path('parent_children/<str:parent_username>/',views.parent_children, name='parent_children'),
    path('parent_signup/', views.parent_signup, name='parent_signup'),
    
    path('parent_list/<str:parent_username>/edit',views.parent_edit, name='parent_edit'),
    path('parent_list/<str:parent_username>/delete_ask',views.parent_delete_ask, name='parent_delete_ask'),
    path('parent_list/<str:parent_username>/delete',views.parent_delete, name='parent_delete'),

    
    
   
]

listings/forms.py
from django import forms 
from listings.models import Grade, Subject, Mark, Salary, GradeAttendance
from users.models import Student
from bootstrap_datepicker_plus.widgets import DatePickerInput



############################ grade form to add grade  #######################################
class GradeForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = ['name', 'description']
#################################################################







########### form as student list to  multiplechoice only attendace students for selected grade ################################################
class GradeAttendanceForm(forms.ModelForm):
    students = forms.ModelMultipleChoiceField(queryset=Student.objects.all(),required=True)
    class Meta:
        model = GradeAttendance
        fields = ['att_date', 'students']
        widgets = {
            # specify date-format
            'att_date': DatePickerInput(format='%Y-%m-%d'),
        }
#################################################################






###################################### SubjectForm #######################################################
class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['title', 'grade', 'description', 'note']
#################################################################






###################################### MarkForm #################################
class MarkForm(forms.ModelForm):
    class Meta:
        model = Mark
        fields = ['exam_name','mark_value','full_value', 'exam_date', 'note']
        widgets = {
            # specify date-format
            'exam_date': DatePickerInput(format='%Y-%m-%d'),
        }

   





###################################### EmailForm #################################
# https://docs.djangoproject.com/en/3.2/topics/forms/#more-on-fields
class EmailForm(forms.Form):
    # subject = forms.CharField(label='', max_length=100,placeholder='Subject')
    # message = forms.CharField(widget=forms.Textarea)
    # sender = forms.EmailField()
    # cc_myself = forms.BooleanField(required=False)

    subject = forms.CharField(max_length=100, label="", required=True,
                                # help_text='please enter Email Subject',
                                error_messages={
                                            'required': 'reqired Subject'},

                                widget=forms.TextInput(attrs={
                                            'placeholder': 'Subject here ..',
                                            'class': 'form-control'})
                                )

    sender = forms.EmailField(max_length=255, label="", required=True,
                              error_messages={'required': 'required email'},
                              widget=forms.TextInput(attrs={
                                  'placeholder': 'Your Email here ..',
                                  'class': 'form-control'})
                              )


    message = forms.CharField(label="", widget=forms.Textarea(attrs={'cols':'15',
                                                                      'rows': 5,
                                                                'placeholder': 'Explain your problem here ..',
                                                                'class': 'form-control', })
                                                                 )
    
    cc_myself = forms.BooleanField(required=False)
#################################################################
                                                                                        

templates/listings/email_us.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        
        <!-- title -->
        <title>Happy School - SB Admin</title>

        <!-- Bootstrap CSS -->
        <link href="{% static 'css/bootstrap.min.css' rel="stylesheet"  %}">

        <!-- mystyle CSS -->
        <link href="{% static 'css/styles.css' %}"  rel="stylesheet"> 
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" type="text/css">
    </head>
  
  
    <body class='mybody pat'>
  

        <div class = 'col-md-6 offset-md-3  p-3 shadow-lg  rounded'>
                <div class="card text-center">
                    
                    
                    <div class="card-header bg-dark text-light p-4">
                        <span><i class="fas fa-school"></i></span> Happy School
                    </div>
                
                    <div class="card-body bg-light">

                            {% include 'includes/messages.html' %}
                            
                            <form method="POST"  novalidate>
                                {% csrf_token %}

                                {%  include 'includes/form_emailus.html' %}

                                <div class='btn-group'>
                                    <button type="submit" class="btn btn-success btn-lg btn-block">Send</button> 
                                </div>
                            </form> 
                    
                    </div>
                </div>
        </div>
      

    
 
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script type="text/javascript" src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  
    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
    {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script> {% endcomment %}
    
    
    <!-- Fontawesome javascript  -->
    <script type="text/javascript" src="{% static 'js/fontawesome.min.js' %}"></script> 
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script> 
    <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>
    
    </body>
</html>

templates/listings/grade_dashboard.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}
<div class="container-fluid">
    <div class="card-header mt-3">
        <i class="fas fa-layer-group"></i>
                Grades Attendance
    </div>


    <div class="row mt-3 mb-3 ">
        {% for grade in grades  %}

            <div class="col-sm-4">
                <div class="card m-1  bg-info">
                    <div class="card-body">
                            Attendance
                            <h5 class="card-title">{{ grade.name }}</h5> 

                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a type="button" class="btn btn-secondary text-white" href="{% url 'listings:attendance_list' grade_slug=grade.slug %}"><i class="far fa-eye"></i>&nbsp;View&nbsp;</a>
                                <a type="button" class="btn btn-secondary text-white" href="{% url 'listings:grade_attendanc_create' grade_slug=grade.slug %}"><i class="fas fa-plus"></i></i>&nbsp;Add</a>   
                            </div>
                     
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>



 
{% endblock %} 

templates/listings/grade_delete_ask.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}

    <div class="container-fluid mt-5 mb-5"> 
        <div class="card">
            <div class="card-header">
                <i class="text-warning fas fa-exclamation-triangle"></i>
                Warning
            </div>
            <div class="card-body p-5">
                <p class="card-text pt-2 pb-5">Are you sure you want to delete <strong>{{grade.name|title}}</strong> from database ?</p> 
                <a class="btn btn-outline-danger btn-sm" href="{% url 'listings:grade_delete' grade_slug=grade.slug %}" >Yes, i am sure to delete </a>
                <a class="btn btn-outline-secondary btn-sm"  href="{% url 'listings:grade_list' %}">Cancel</a>
            </div>
        </div>    
   </div>

  {% endblock content %}  

templates/listings/grade_edit.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}


<div class="container-fluid">
    <h3 class="mt-4">{{title|title}}</h3>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">{{sub_title|title}}</li>
    </ol>


    <div class='mb-5 container col-md-6 offset-md-3'>
        <form method="POST"  enctype="multipart/form-data"   novalidate>
            {% csrf_token %}

            {%  include 'includes/form_grade.html' %}

            
            <div class='btn-group'>
                <button type="submit"  class="btn btn-info">Edit</button>
               
            </div>
        </form>     
    </div>

</div>
{% endblock content %}

templates/listings/mark_list.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}
mark list
{% endblock %}

templates/listings/parent_list.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}

    

    <div class="container-fluid">
      
        <ol class="breadcrumb mb-4 mt-5">
            <li class="breadcrumb-item active">Parents</li>
        </ol>
      
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Parents Table
            </div>
            {% if request.user.is_authenticated and request.user.schooladmin.is_schadmin %}
                <div class='ml-4 mt-3'>
                    <a class='btn btn-sm btn-info'  href="{% url 'users:parent_signup' %}"><i class="fas fa-user-plus"></i></a>
                </div>
            {% endif %}

            <div class='row p-3'>
                <div class="col-sm-12 col-md-12 float-right">
                    <form  action="{% url 'listings:parent_list' %}" method="GET" class="d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0 float-right">
                        <div class="input-group">
                            <label class='col-form-label'><small>Search for Parent:&nbsp;</small></label>
                            <input name="sch_ptfathfname"  type="text" class="form-control form-control-sm"  placeholder="Father First Name..."/>
                            <input name="sch_ptfathusername"  type="text" class="form-control form-control-sm"  placeholder="Parent Username..."/>
                            <input name="sch_ptstusername" type="text" class="form-control form-control-sm"  placeholder="Student Username..."/>
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-sm btn-dark"><span style='font-size:0.8rem;'><i class="fas fa-search"></i></span></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>






            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-sm" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Father Full Name</th>
                                <th>Username</th>
                                <th>Parent of Students</th>
                                <th>Father mobile</th>
                                <th>Mother Full Name</th>
                                <th>Mother mobile</th>
                         
                                {% if request.user.is_authenticated and request.user.schooladmin.is_schadmin %}
                                <th>Action</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Father Full Name</th>
                                <th>Username</th>
                                <th>Parent of Students</th>
                                <th>Father mobile</th>
                                <th>Mother Full Name</th>
                                <th>Mother mobile</th>
                              
                                {% if request.user.is_authenticated and request.user.schooladmin.is_schadmin %}
                                <th>Action</th>
                                {% endif %}
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for parent in parents %}
                            <tr>
                                <td><a href="{% url 'listings:parent_detail' parent_username=parent.given_username %}">{{parent.get_father_full_name|title}}</a></td>
                                <td>{{parent.given_username}}</td>
                                <td>
                                    <lu>
                                        {% for student in parent.students.all %}
                                            <li><a href="{% url 'listings:student_detail' student_username=student.given_username %}">{{ student }}</a></li>  
                                        {% endfor %}
                                    </lu>
                                </td> 
                                <td>{{parent.father_mobile}}</td>
                                <td>{{parent.mother_fl_name}}</td>
                                <td>{{parent.mother_mobile}}</td>
                        
                                {% if request.user.is_authenticated and request.user.schooladmin.is_schadmin %}
                                    <td>
                                        <a class="btn btn-info btn-sm  btn-circle m-1" href="{% url 'users:parent_edit' parent_username=parent.given_username %}"><i class="far fa-edit"></i></a>
                                        <a class="btn btn-danger btn-sm btn-circle m-1" href="{% url 'users:parent_delete_ask' parent_username=parent.given_username %}"><i class="far fa-trash-alt"></i></a>
                                    </td>
                                {% endif %}
                            </tr>
                            {% empty %}
                                <p class='text-danger'>Sorry no parent in this table</p>
                            {% endfor %}
                        </tbody>
                    </table>



                    <!-- pagination-->
                    {% if parents.has_other_pages %}
                        <div>
                            <nav aria-label="Page navigation conatiner"></nav>
                                <ul class="pagination pagination-sm justify-content-center">
                                    {% if students.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ parents.previous_page_number }}">
                                                &laquo; Previous 
                                            </a>
                                        </li>
                                    {% endif %}

                                    {% for page_number in parents.paginator.page_range %}
                                        {% if page_number == parents.number %}
                                            <li  class="page-item active">
                                                <span class="page-link">{{ page_number }}
                                                    <span class="sr-only">(current)</span>
                                                </span>
                                            </li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                                        {% endif %}
                                    {% endfor %}

                                    {% if students.has_next %}
                                        <li class="page-item" >
                                            <a class="page-link" href="?page={{ parents.next_page_number }}">
                                                Next &raquo;
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    {% endif %}
                    <!-- pagination end-->


                </div>
            </div>
        </div>
     
    </div> 
    
{% endblock %}

templates/listings/subject_mark_student_list.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}


    <div class="container-fluid">
      
        <ol class="breadcrumb mb-4 mt-5">
            <li class="breadcrumb-item active">Students &nbsp;<span class="badge badge-info">{{ grade.name|title }}</span></li>👍
        </ol>
    
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
               Students Table Mark for <span class="badge badge-primary">{{ subject.title|title }}</span>&nbsp;<span class="badge badge-info">{{ grade.name|title }}</span> 
            </div>
            


            <!-- student list table -->
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-sm" id="dataTable" width="100%" cellspacing="0">
                        <thead class='text-center'>
                            <tr>
                                <th>Full Name</th>
                                <th>Username</th>
                                <th>View Marks</th>
                                {% if request.user.is_authenticated and request.user.teacher.is_teacher %}
                                <th>Add Mark</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tfoot class='text-center'>
                            <tr>
                                <th>Full Name</th>
                                <th>Username</th>
                                <th>View Marks</th>
                                {% if request.user.is_authenticated and request.user.teacher.is_teacher %}
                                <th>Add Mark</th>
                                {% endif %}
                            </tr>
                        </tfoot>
                        <tbody>
                            {% for student in students %}
                            <tr>
                                <td><a href="{% url 'listings:student_detail' student_username=student.given_username %}">{{student.get_student_full_name|title}}</a></td>
                                <td>{{student.given_username}}</td>
                              
                                <td class='text-center'>
                                    <a class="btn btn-warning btn-sm btn-circle m-1" href="{% url 'listings:subject_mark_student_detail' grade_slug=grade.slug subject_slug=subject.slug student_username=student.given_username %}"><i class="fas fa-stream"></i></a>
                                </td>
                                {% if request.user.is_authenticated and request.user.teacher.is_teacher %}        
                                    <td class='text-center'>
                                        <a class="btn btn-success btn-sm btn-circle m-1" href="{% url 'listings:mark_create' subject_slug=subject.slug student_username=student.given_username %}"><i class="fas fa-plus"></i></a>
                                    </td>
                                {% endif %}
                                    
                            </tr>
                            {% empty %}
                                <p class='text-danger'>Sorry no student in this table</p>
                            {% endfor %}
                        </tbody>
                    </table>



                    <!-- pagination-->
                    {% if students.has_other_pages %}
                        <div>
                            <nav aria-label="Page navigation conatiner"></nav>
                                <ul class="pagination pagination-sm justify-content-center">
                                    {% if students.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ students.previous_page_number }}">
                                                &laquo; Previous 
                                            </a>
                                        </li>
                                    {% endif %}

                                    {% for page_number in students.paginator.page_range %}
                                        {% if page_number == students.number %}
                                            <li  class="page-item active">
                                                <span class="page-link">{{ page_number }}
                                                    <span class="sr-only">(current)</span>
                                                </span>
                                            </li>
                                        {% else %}
                                            <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
                                        {% endif %}
                                    {% endfor %}

                                    {% if students.has_next %}
                                        <li class="page-item" >
                                            <a class="page-link" href="?page={{ students.next_page_number }}">
                                                Next &raquo;
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    {% endif %}
                    <!-- pagination end-->


                </div>
            </div>
        </div>
    
          
    
    
    
    </div> 
    
{% endblock %}