listings/urls.py
from django.urls import path
from .import views


app_name ='listings'
urlpatterns =[
    
    # email_us 
    path('Email_us/',views.Email_us, name='Email_us'),
    
    # index
    path('', views.index, name='index'),
    
    # grade 
    path('grade_signup/',views.grade_signup, name='grade_signup'),
    path('grade_list/', views.grade_list, name='grade_list'),
    path('grade_list/detail/<slug:grade_slug>/',views.grade_detail, name='grade_detail'),
    path('grade_list/edit/<slug:grade_slug>/',views.grade_edit, name='grade_edit'),
    path('grade_list/delete_ask/<slug:grade_slug>/',views.grade_delete_ask, name='grade_delete_ask'),
    path('grade_list/delete/<slug:grade_slug>/',views.grade_delete, name='grade_delete'),
    # grade attendance students
    path('grade_attendance/<slug:grade_slug>/create/',views.grade_attendanc_create, name='grade_attendanc_create'),
    path('grades_dashboard/', views.grade_dashboard, name='grade_dashboard'),
    path('grade_attendance/<slug:grade_slug>/list/',views.attendance_list, name='attendance_list'),
    # path('grade_attendance/<slug:grade_slug>/',views.grade_attendanc, name='grade_attendanc'),
   
   # subject 
    path('subject_signup/',views.subject_signup, name='subject_signup'),
    path('subject_list/',views.subject_list, name='subject_list'),
    path('subject_list/detail/<slug:subject_slug>/',views.subject_detail, name='subject_detail'),
    path('subject_list/edit/<slug:subject_slug>/',views.subject_edit, name='subject_edit'),
    path('subject_list/delete_ask/<slug:subject_slug>/',views.subject_delete_ask, name='subject_delete_ask'),
    path('subject_list/delete/<slug:subject_slug>/',views.subject_delete, name='subject_delete'),
    path('subject_grade_dashboard/', views.subject_grade_dashboard, name='subject_grade_dashboard'),
    path('subject_mark_student_list/<slug:grade_slug>/<slug:subject_slug>/', views.subject_mark_student_list,
         name='subject_mark_student_list'),
    path('subject_mark_student_detail/<slug:grade_slug>/<slug:subject_slug>/<str:student_username>/', views.subject_mark_student_detail,
         name='subject_mark_student_detail'),

    # mark
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/mark_add/',views.mark_create, name='mark_create'),
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/<int:mark_id>/mark_edit/',views.mark_edit, name='mark_edit'),
    # path('mark/<str:student_username>/create/',views.mark_student_create, name="mark_student_create"),

    # user
    path('user_list/', views.user_list,name='user_list'),
    
    # school admin
    path('schadmin_list/',views.schadmin_list,name='schadmin_list'),
    path('schadmin_list/detail/<str:schadmin_username>/',views.schadmin_detail, name='schadmin_detail'),
    
    # teacher
    path('teacher_list/',views.teacher_list,name='teacher_list'),
    path('teacher_list/detail/<str:teacher_username>/',views.teacher_detail, name='teacher_detail'),
  
    # student
    path('student_list/',views.student_list,name='student_list'),
    path('student_list/detail/<str:student_username>/',views.student_detail, name='student_detail'),
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/mark/',views.student_subject_mark_detail, name='student_subject_mark_detail'),
   
    path('student_list/detail/<str:student_username>/marks',views.student_detail_marks, name='student_detail_marks'),
    path('student_list/detail/<str:student_username>/attendance',views.student_detail_attendance, name='student_detail_attendance'),
    path('student_list/detail/<str:student_username>/messages',
         views.student_detail_messages, name='student_detail_messages'),
    
    # parent
    path('parent_list/', views.parent_list, name='parent_list'),
    path('parent_list/detail/<str:parent_username>/',views.parent_detail, name='parent_detail'),
    
    # charts
    path('charts_all/', views.charts_all, name='charts_all'),
 
]

sch_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('listings.urls', namespace='listings')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from.import views


app_name = 'users'
urlpatterns = [
    # login
    path('login/', views.login_user, name='login_user'),
    # logout
    path('logout/', views.logout_user, name='logout_user'),
    # profile
    path('profile/',views.profile,name='profile'),
    # image update
    path('image_update/<str:user_username>/',views.image_user_update, name='image_user_update'),
    
    # main dashboard
    path('main_dashboard/', views.main_dashboard, name='main_dashboard'),

    # webadmin 
    path('webadmin_profile/', views.webadmin_profile, name='webadmin_profile'),
    path('webadmin_dashboard/<str:webadmin_username>/',views.webadmin_dashboard, name='webadmin_dashboard'),

    # Academic Year
    path('academicyear_add/', views.academicyear_add, name='academicyear_add'),
    path('academicyear_edit/<str:year_name>/',views.academicyear_edit, name='academicyear_edit'),
    path('academicyear_delete/<str:year_name>/',views.academicyear_delete, name='academicyear_delete'),
   

    # schooladmin
    path('schadmin_profile/', views.schadmin_profile, name='schadmin_profile'),
    path('schadmin_dashboard/<str:schadmin_username>/',views.schadmin_dashboard, name='schadmin_dashboard'),
    path('schooladmin_signup/', views.schadmin_signup, name='schadmin_signup'),
    path('schooladmin_list/<str:schadmin_username>/edit',views.schadmin_edit, name='schadmin_edit'),
    path('schooladmin_list/<str:schadmin_username>/delete_ask/',views.schadmin_delete_ask, name='schadmin_delete_ask'),
    path('schooladmin_list/<str:schadmin_username>/delete',views.schadmin_delete, name='schadmin_delete'),

    # teacher
    path('teacher_profile/', views.teacher_profile, name='teacher_profile'),
    path('teacher_dashboard/<str:teacher_username>/', views.teacher_dashboard,name='teacher_dashboard'),
    path('teacher_signup/', views.teacher_signup, name='teacher_signup'),
    path('teacher_list/<str:teacher_username>/edit',views.teacher_edit, name='teacher_edit'),
    path('teacher_list/<str:teacher_username>/delete_ask',views.teacher_delete_ask, name='teacher_delete_ask'),
    path('teacher_list/<str:teacher_username>/delete',views.teacher_delete, name='teacher_delete'),
    path('teacher_smessage/<str:student_username>/',views.message_t_student_send, name='message_t_student'),
    path('teacher_gmessage/<slug:grade_slug>/',views.message_t_grade_send, name='message_t_grade'),
    
    # student
    path('student_profile/', views.student_profile, name='student_profile'),
    path('student_dashboard/<str:student_username>/',views.student_dashboard, name='student_dashboard'),
    path('student_signup/', views.student_signup, name='student_signup'),
    path('student_list/<str:student_username>/edit',views.student_edit, name='student_edit'),
    path('student_list/<str:student_username>/delete_ask',views.student_delete_ask, name='student_delete_ask'),
    path('student_list/<str:student_username>/delete',views.student_delete, name='student_delete'),
    
    
    # parent
    path('parent_profile/', views.parent_profile, name='parent_profile'),
    
    path('parent_student_dashboard/<str:student_username>/',
         views.parent_student_dashboard, name='parent_student_dashboard'),
    path('parent_children/<str:parent_username>/',views.parent_children, name='parent_children'),
    path('parent_signup/', views.parent_signup, name='parent_signup'),
    
    path('parent_list/<str:parent_username>/edit',views.parent_edit, name='parent_edit'),
    path('parent_list/<str:parent_username>/delete_ask',views.parent_delete_ask, name='parent_delete_ask'),
    path('parent_list/<str:parent_username>/delete',views.parent_delete, name='parent_delete'),

    
    
   
]

templates/base_index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        
        <!-- title -->
        <title>Happy School</title>

        <!-- Bootstrap CSS -->
        <link href="{% static 'css/bootstrap.min.css' rel="stylesheet"  %}">

        <!-- mystyle CSS -->
        <link href="{% static 'css/styles.css' %}"  rel="stylesheet"> 
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" type="text/css">
    </head>


    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'listings:index' %}"><span><i class="fas fa-school"></i></span> Happy School</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto mr-5">
                    <li class="nav-item dropdown mr-5">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fas fa-user fa-fw"></i>
                            </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% if request.user.is_authenticated %} 
                                 <p> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Welcome <strong>{{request.user.first_name|title }}</strong></p>
                            <a class="dropdown-item" href="{% url 'users:profile' %}"><i class="far fa-id-badge"></i>&nbsp;Profile</a>
                            
                            {% if request.user.schooladmin.is_schadmin %}
                                <a class="dropdown-item" href="{% url 'users:schadmin_dashboard' schadmin_username=request.user.username %}"><i class="fas fa-tasks"></i>&nbsp;Dashboard</a>
                            {% elif request.user.teacher.is_teacher %}
                                <a class="dropdown-item" href="{% url 'users:teacher_dashboard' teacher_username=request.user.username %}"><i class="fas fa-tasks"></i></i>&nbsp;Dashboard</a>
                            {% elif request.user.student.is_student %}
                                <a class="dropdown-item" href="{% url 'users:student_dashboard' student_username=request.user.username %}"><i class="fas fa-tasks"></i></i>&nbsp;Dashboard</a>
                            {% elif request.user.is_parent %}
                                <a class="dropdown-item" href="{% url 'users:parent_children' parent_username=request.user.username %}"><i class="fas fa-tasks"></i></i>&nbsp;Dashboard</a>
                            {% elif request.user.is_staff and request.user.is_superuser %}
                                <a class="dropdown-item" href="{% url 'users:webadmin_dashboard' webadmin_username=request.user.username %}"><i class="fas fa-tasks"></i></i>&nbsp;Dashboard</a> 
                            {% endif %}
                            <hr>
                            <a class="dropdown-item" href="{% url 'users:logout_user' %}"><i class="fas fa-sign-out-alt"></i>&nbsp;Logout</a>
                            {% else %}
                                <a class="dropdown-item" href="{% url 'users:login_user' %}"><i class="fas fa-sign-in-alt"></i>&nbsp;Login</a>    
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
      {% block content %}





      {% endblock content %}       
      <!-- FOOTER -->
      <!--  start footer of main list -->
        <footer class="py-4 bg-light mt-auto">
            <div class="container">
                <div class="align-items-center small">     
                    <center>
                        <p class="text-muted">
                        Copyright&copy;{% now 'Y' %},Happy School<br>All rights reserved 
                        </p>
                    </center>
                </div>
            </div>
        </footer>
        <footer class="footer navbar-dark bg-dark small mb-0 mb-0">
            <div class="text-muted mr-3 float-right">
                <small>Developed by:&nbsp;<a href='https://github.com/mayals'><i class="fab fa-github"></i><a>@mayals</small>&nbsp;&nbsp;
                <small><a href="mailto:developer.web.dj@gmail.com"><i class="far fa-envelope"></i>&nbsp;</a>developer.web.dj@gmail.com</small> 
            </div>    
        </footer>
          <!--  end footer of main list -->

       


        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script type="text/javascript" src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      
        <!-- Option 2: jQuery, Popper.js, and Bootstrap JS -->
        {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script> {% endcomment %}
        
        
        <!-- Fontawesome javascript  -->
        <script type="text/javascript" src="{% static 'js/fontawesome.min.js' %}"></script>
        
        <!-- Add active state to sidbar nav links-->
        <script src="{% static 'js/scripts.js' %}"></script>
        
    
    </body>
</html>