listings/urls.py
from django.urls import path
from .import views


app_name ='listings'
urlpatterns =[
    
    # email_us 
    path('Email_us/',views.Email_us, name='Email_us'),
    
    # index
    path('', views.index, name='index'),
    
    # grade 
    path('grade_signup/',views.grade_signup, name='grade_signup'),
    path('grade_list/', views.grade_list, name='grade_list'),
    path('grade_list/detail/<slug:grade_slug>/',views.grade_detail, name='grade_detail'),
    path('grade_list/edit/<slug:grade_slug>/',views.grade_edit, name='grade_edit'),
    path('grade_list/delete_ask/<slug:grade_slug>/',views.grade_delete_ask, name='grade_delete_ask'),
    path('grade_list/delete/<slug:grade_slug>/',views.grade_delete, name='grade_delete'),
    # grade attendance students
    path('grade_attendance/<slug:grade_slug>/create/',views.grade_attendanc_create, name='grade_attendanc_create'),
    path('grades_dashboard/', views.grade_dashboard, name='grade_dashboard'),
    path('grade_attendance/<slug:grade_slug>/list/',views.attendance_list, name='attendance_list'),
    # path('grade_attendance/<slug:grade_slug>/',views.grade_attendanc, name='grade_attendanc'),
   
   # subject 
    path('subject_signup/',views.subject_signup, name='subject_signup'),
    path('subject_list/',views.subject_list, name='subject_list'),
    path('subject_list/detail/<slug:subject_slug>/',views.subject_detail, name='subject_detail'),
    path('subject_list/edit/<slug:subject_slug>/',views.subject_edit, name='subject_edit'),
    path('subject_list/delete_ask/<slug:subject_slug>/',views.subject_delete_ask, name='subject_delete_ask'),
    path('subject_list/delete/<slug:subject_slug>/',views.subject_delete, name='subject_delete'),
    path('subject_grade_dashboard/', views.subject_grade_dashboard, name='subject_grade_dashboard'),
    path('subject_mark_student_list/<slug:grade_slug>/<slug:subject_slug>/', views.subject_mark_student_list,
         name='subject_mark_student_list'),
    path('subject_mark_student_detail/<slug:grade_slug>/<slug:subject_slug>/<str:student_username>/', views.subject_mark_student_detail,
         name='subject_mark_student_detail'),

    # mark
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/mark_add/',views.mark_create, name='mark_create'),
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/<int:mark_id>/mark_edit/',views.mark_edit, name='mark_edit'),
    # path('mark/<str:student_username>/create/',views.mark_student_create, name="mark_student_create"),

    # user
    path('user_list/', views.user_list,name='user_list'),
    
    # school admin
    path('schadmin_list/',views.schadmin_list,name='schadmin_list'),
    path('schadmin_list/detail/<str:schadmin_username>/',views.schadmin_detail, name='schadmin_detail'),
    
    # teacher
    path('teacher_list/',views.teacher_list,name='teacher_list'),
    path('teacher_list/detail/<str:teacher_username>/',views.teacher_detail, name='teacher_detail'),
  
    # student
    path('student_list/',views.student_list,name='student_list'),
    path('student_list/detail/<str:student_username>/',views.student_detail, name='student_detail'),
    path('student_list/detail/<str:student_username>/<slug:subject_slug>/mark/',views.student_subject_mark_detail, name='student_subject_mark_detail'),
   
    path('student_list/detail/<str:student_username>/marks',views.student_detail_marks, name='student_detail_marks'),
    path('student_list/detail/<str:student_username>/attendance',views.student_detail_attendance, name='student_detail_attendance'),
    path('student_list/detail/<str:student_username>/messages',
         views.student_detail_messages, name='student_detail_messages'),
    
    # parent
    path('parent_list/', views.parent_list, name='parent_list'),
    path('parent_list/detail/<str:parent_username>/',views.parent_detail, name='parent_detail'),
    
    # charts
    path('charts_all/', views.charts_all, name='charts_all'),
 
]

sch_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('listings.urls', namespace='listings')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from.import views


app_name = 'users'
urlpatterns = [
    # login
    path('login/', views.login_user, name='login_user'),
    # logout
    path('logout/', views.logout_user, name='logout_user'),
    # profile
    path('profile/',views.profile,name='profile'),
    # image update
    path('image_update/<str:user_username>/',views.image_user_update, name='image_user_update'),
    
    # main dashboard
    path('main_dashboard/', views.main_dashboard, name='main_dashboard'),

    # webadmin 
    path('webadmin_profile/', views.webadmin_profile, name='webadmin_profile'),
    path('webadmin_dashboard/<str:webadmin_username>/',views.webadmin_dashboard, name='webadmin_dashboard'),

    # Academic Year
    path('academicyear_add/', views.academicyear_add, name='academicyear_add'),
    path('academicyear_edit/<str:year_name>/',views.academicyear_edit, name='academicyear_edit'),
    path('academicyear_delete/<str:year_name>/',views.academicyear_delete, name='academicyear_delete'),
   

    # schooladmin
    path('schadmin_profile/', views.schadmin_profile, name='schadmin_profile'),
    path('schadmin_dashboard/<str:schadmin_username>/',views.schadmin_dashboard, name='schadmin_dashboard'),
    path('schooladmin_signup/', views.schadmin_signup, name='schadmin_signup'),
    path('schooladmin_list/<str:schadmin_username>/edit',views.schadmin_edit, name='schadmin_edit'),
    path('schooladmin_list/<str:schadmin_username>/delete_ask/',views.schadmin_delete_ask, name='schadmin_delete_ask'),
    path('schooladmin_list/<str:schadmin_username>/delete',views.schadmin_delete, name='schadmin_delete'),

    # teacher
    path('teacher_profile/', views.teacher_profile, name='teacher_profile'),
    path('teacher_dashboard/<str:teacher_username>/', views.teacher_dashboard,name='teacher_dashboard'),
    path('teacher_signup/', views.teacher_signup, name='teacher_signup'),
    path('teacher_list/<str:teacher_username>/edit',views.teacher_edit, name='teacher_edit'),
    path('teacher_list/<str:teacher_username>/delete_ask',views.teacher_delete_ask, name='teacher_delete_ask'),
    path('teacher_list/<str:teacher_username>/delete',views.teacher_delete, name='teacher_delete'),
    path('teacher_smessage/<str:student_username>/',views.message_t_student_send, name='message_t_student'),
    path('teacher_gmessage/<slug:grade_slug>/',views.message_t_grade_send, name='message_t_grade'),
    
    # student
    path('student_profile/', views.student_profile, name='student_profile'),
    path('student_dashboard/<str:student_username>/',views.student_dashboard, name='student_dashboard'),
    path('student_signup/', views.student_signup, name='student_signup'),
    path('student_list/<str:student_username>/edit',views.student_edit, name='student_edit'),
    path('student_list/<str:student_username>/delete_ask',views.student_delete_ask, name='student_delete_ask'),
    path('student_list/<str:student_username>/delete',views.student_delete, name='student_delete'),
    
    
    # parent
    path('parent_profile/', views.parent_profile, name='parent_profile'),
    
    path('parent_student_dashboard/<str:student_username>/',
         views.parent_student_dashboard, name='parent_student_dashboard'),
    path('parent_children/<str:parent_username>/',views.parent_children, name='parent_children'),
    path('parent_signup/', views.parent_signup, name='parent_signup'),
    
    path('parent_list/<str:parent_username>/edit',views.parent_edit, name='parent_edit'),
    path('parent_list/<str:parent_username>/delete_ask',views.parent_delete_ask, name='parent_delete_ask'),
    path('parent_list/<str:parent_username>/delete',views.parent_delete, name='parent_delete'),

    
    
   
]

templates/users/parent_delete_ask.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}

    <div class="container-fluid mt-5 mb-5"> 

    <ol class="breadcrumb mb-4 mt-5">
            <li class="breadcrumb-item active">Parent Delete</li>
    </ol>

        <div class="card">
            <div class="card-header">
                <i class="text-warning fas fa-exclamation-triangle"></i>
                Warning
            </div>
            <div class="card-body p-5">
                <p class="card-text pt-2 pb-5">Are you sure you want to delete <strong>{{parent.get_student_full_name|title}}</strong> register from database ?</p> 
                <a class="btn btn-outline-danger btn-sm" href="{% url 'users:parent_delete' parent_username=parent.given_username %}" >Yes, i am sure to delete </a>
                <a class="btn btn-outline-secondary btn-sm"  href="{% url 'listings:parent_list' %}">Cancel</a>
            </div>
        </div>    
   </div>

  {% endblock content %}  

templates/users/parent_profile.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}


<div class="container-fluid">

    <h5 class="mt-4">Parent Profile</h5>


        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active"> {{ parent.get_father_full_name|title }}</li>
        </ol>   
    
    
        <div class="row">

            <div class="col-sm-12 col-md-12  mb-5">
                <div class="card card-box">
                    <div class="card-header text-center">
                        Parent of sudents :
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                                <div class='row'>
                            {% for student in parent.students.all %}
                               
                           
                                <div class=' col-sm-12 col-md-4 mt-1 mb-1'>
                                    <a href="{% url 'listings:student_detail' student_username=student.given_username %}" class='btn btn-light'>
                                        <img src="{{student.user.imageuser.image.url}}" style="width:80px;high:80px;" class="card-img img-thumbnail" alt="{{student.get_student_full_name}}">
                                        {{ student.get_student_full_name}}
                                    </a>
                                </div>
                             
                              
                            {% endfor %}
                               </div>
                        </blockquote>
                    </div>
                </div>
            </div>
        
        </div>

        
        <div >
            <h5 class="card-title">Parent Informations</h5>
        </div>    
                    
    
        <div class="row">

            <div class="col-sm-6 col-md-6  mb-5">
                <div class="card card-box">
                    <div class="card-header">
                        Father Information
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p class='card-text font-italic'><small class='text-muted'>Father Full Name:&nbsp;</small><small>{{ parent.get_father_full_name|title }}</small></p>
                            <p class='card-text font-italic'><small class='text-muted'>Father First Name:&nbsp;</small><small>{{ parent.father_f_name|title }}</small></p>
                            <p class='card-text font-italic'><small class='text-muted'>Father Second Name:&nbsp;</small><small>{{ parent.father_l_name|title }}</small></p>
                            <p class='card-text font-italic' ><small class='text-muted'>Father Email:&nbsp;</small><small>{{ parent.father_email|title }}</small></p>
                            <p class='card-text font-italic' ><small class='text-muted'>Father Mobile:&nbsp;</small><small>{{ parent.father_mobile }}</small></p>
                            <p class='card-text font-italic' ><small class='text-muted'>Father Nationality:&nbsp;</small><small>{{ parent.father_nationality|title }}</small></p>
                            <p class='card-text font-italic' ><small class='text-muted'>Father Passport Number:&nbsp;</small><small>{{ parent.father_passport_no }}</small></p>
                            <p class='card-text font-italic' ><small class='text-muted'>Father Address:&nbsp;</small><small>{{ parent.father_address }}</small></p>
                        </blockquote>
                    </div> 
                </div>
            </div>

            <div class="col-sm-12 col-md-6  mb-5">
                <div class="card card-box">
                    <div class="card-header">
                        Mother Information
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p class='card-text font-italic' ><small class='text-muted'>Mother Full Name:&nbsp;</small><small>{{ parent.mother_fl_name|title }}</small></p>
                            <p class='card-text font-italic' ><small class='text-muted'>Mother Mobile:&nbsp;</small><small>{{ parent.mother_mobile|title }}</small></p>
                        </blockquote>
                    </div>
                </div>
            </div> 
                    
        </div>


        


        <div class="row">

            <div class="col-sm-12 col-md-12  mb-5">
                <div class="card card-box">
                    <div class="card-header text-center">
                        Parent Note about their children
                    </div>
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p class='card-text font-italic' ><small>{{ parent.note|title }}</small></p>  
                        </blockquote>
                    </div>
                </div>
            </div>
        
        </div>
        

        <div>
            <div class="col-sm-12 col-md-6  mb-5">    
                <blockquote>
                   
                    <p>This parent informations </p>
                    <p class='card-text font-italic' ><small class='text-muted'>Add at:&nbsp;</small><small>{{ parent.created_at }} ago</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Add by:&nbsp;</small><small>{{ parent.created_by }}</small></p>
                    <hr>
                    <p class='card-text font-italic' ><small class='text-muted'>Last Update at:&nbsp;</small><small>{{ parent.updated_at  }} ago</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Last Update by:&nbsp;</small><small>{{ parent.updated_by }}</small></p>
                </blockquote>
            </div>
        </div>
  
               
    <div class='row'>   
        <div class="col-sm-12 col-md-4  mb-5">
            <div class="card card-box">
                <div class="card-header">
                    Lorem ipsum
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4  mb-5">
            <div class="card card-box">
                <div class="card-header">
               Lorem ipsum
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4 mb-30">
            <div class="card card-box">
                <div class="card-header">
                    Lorem ipsum
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>



</div>

{% endblock %}

templates/users/parent_student_dashboard.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% include 'includes/messages.html' %}


<div class="container-fluid">
        
        {% if academicyear %}
           <h5 class='text-secondary font-italic'>{{academicyear.name }}</h5>
        {% endif %}

        <h5 class="mt-4"> Student Dasboard</h5>
        
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Student Dasboard</li>
        </ol>


    <div class="row">
        <div class="col-xl-12">
            <div class="card mb-4">
                
                <div class="card-header">
                        <i class="fas fa-users mr-1"></i>
                        Student Manager / {{ student.get_student_full_name|title }}&nbsp;<span class="p-2 badge badge-info">{{student.grade}}</span>
                </div>
                <div class="card-body"> 
                   
                    <div class='row'>    
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-darkblue text-white mb-4">
                                <div class="card-body text-center"><strong>Student Mark</strong></div>
                                <div class="card-footer text-center">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a type="button" class="btn btn-dark" href={% url 'listings:student_detail_marks' student_username=student.given_username %}>&nbsp;Detail&nbsp;<i class="fas fa-angle-double-right"></i></a>  
                                    </div>
                                </div>
                            </div>
                        </div>
                            
                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-warning text-white mb-4">
                                <div class="card-body text-center"><strong>Student Attendance</strong></div>
                                <div class="card-footer text-center">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a type="button" class="btn btn-dark" href={% url 'listings:student_detail_attendance' student_username=student.given_username %}>&nbsp;Detail&nbsp;<i class="fas fa-angle-double-right"></i></a> 
                                        
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-orange text-white mb-4">
                                <div class="card-body text-center"><strongs>Student Messages</strong></div>
                                <div class="card-footer text-center">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a type="button" class="btn btn-dark" href={% url 'listings:student_detail_messages' student_username=student.given_username %}>&nbsp;Detail&nbsp;<i class="fas fa-angle-double-right"></i></a> 
                                          
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-3 col-md-6">
                            <div class="card bg-success text-white mb-4">
                                <div class="card-body text-center"><strong>My Profile</strong></div>
                                <div class="card-footer text-center">
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a type="button" class="btn btn-dark" href={% url 'users:parent_profile' %}>&nbsp;Detail&nbsp;<i class="fas fa-angle-double-right"></i></a> 
                                          
                                    </div>
                                </div>
                            </div>
                        </div>
 
                    </div>
                </div>


            </div>
        </div>
    </div>



</div>
{% endblock %}

templates/users/schadmin_delete_ask.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}

    <div class="container-fluid mt-5 mb-5"> 
        <div class="card">
            <div class="card-header">
                <i class="text-warning fas fa-exclamation-triangle"></i>
                Warning
            </div>
            <div class="card-body p-5">
                <p class="card-text pt-2 pb-5">Are you sure you want to delete <strong>{{schadmin.get_schadmin_full_name|title}}</strong> register from database ?</p> 
                <a class="btn btn-outline-danger btn-sm" href="{% url 'users:schadmin_delete' schadmin_username=schadmin.get_schadmin_username %}" >Yes, i am sure to delete </a>
                <a class="btn btn-outline-secondary btn-sm"  href="{% url 'listings:schadmin_list' %}">Cancel</a>
            </div>
        </div>    
   </div>

  {% endblock content %}  

templates/users/student_delete_ask.html
{% extends 'base.html' %}
{% block content %}


  {% include 'includes/messages.html' %}

    <div class="container-fluid">
        
        
        <h3 class="mt-4">{{title|title}}</h3>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">{{sub_title|title}}</li>
        </ol>
        
        <div class="card">
            <div class="card-header">
                <i class="text-warning fas fa-exclamation-triangle"></i>
                Warning
            </div>
            <div class="card-body p-5">
                <p class="card-text pt-2 pb-5">Are you sure you want to delete <strong>{{student.get_student_full_name|title}}</strong> register from database ?</p> 
                <a class="btn btn-outline-danger btn-sm" href="{% url 'users:student_delete' student_username=student.given_username %}" >Yes, i am sure to delete </a>
                <a class="btn btn-outline-secondary btn-sm"  href="{% url 'listings:student_list' %}">Cancel</a>
            </div>
        </div>    
   
   
   </div>

  {% endblock content %}  

templates/users/teacher_delete_ask.html
{% extends 'base.html' %}
{% block content %}
 
{% include 'includes/messages.html' %}

    <div class="container-fluid mt-5 mb-5"> 
        <div class="card">
            <div class="card-header">
                <i class="text-warning fas fa-exclamation-triangle"></i>
                Warning
            </div>
            <div class="card-body p-5">
                <p class="card-text pt-2 pb-5">Are you sure you want to delete <strong>{{teacher.get_teacher_full_name|title}}</strong> register from database ?</p> 
                <a class="btn btn-outline-danger btn-sm" href="{% url 'users:teacher_delete' teacher_username=teacher.given_username %}" >Yes, i am sure to delete </a>
                <a class="btn btn-outline-secondary btn-sm"  href="{% url 'listings:teacher_list' %}">Cancel</a>
            </div>
        </div>    
   </div>

  {% endblock content %}  

templates/users/teacher_profile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% include 'includes/messages.html' %}


<div class="container-fluid">

<h5 class="mt-4">{{ title }}&nbsp;&nbsp;</h5>

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active"><span><strong>{{ user.teacher.get_teacher_full_name|title }}</strong> profile</span></li>
</ol>

    <div class="card card-body mb-5">
    <div class='mb-1'><small><span class="text-muted float-right">Last Login:&nbsp;&nbsp;{{user.last_login|timesince}} ago </span><small></div>
        <div class='row'>
            <div class="col-md-2 text-center">
                {% if request.user.imageuser.image %}
                    <img src="{{request.user.imageuser.image.url}}" class="card-img img-thumbnail" alt="{{teacher.get_teacher_full_name}}">
                {% else %}
                    <img src="{% static 'image/default_user.jpg' %}" class="card-img img-thumbnail" alt="{{teacher.get_teacher_full_name}}">
                {% endif %}
            <a  href="{% url 'users:image_user_update' user_username=user.username %}" class="btn btn-secondary btn-sm mt-1 mb-1">Update Image</a>
            </div>
           
            <div class="col-md-10">
                <div class="card-header">
                    <h5 class="card-title">Personal Informations</h5>
                </div>    
                <blockquote class="blockquote mb-0">
                    <p class='card-text font-italic'><small class='text-muted'>Full Name:&nbsp;</small><small>{{ user.teacher.get_teacher_full_name|title }}</small></p>
                    <p class='card-text text-info font-italic'><small class='text-muted'>username:&nbsp;</small><small><strong>{{ user.username}}</strong></small></p>
                    <p class='card-text font-italic'><small class='text-muted'>First Name:&nbsp;</small><small>{{ user.teacher.first_name|title }}</small></p>
                    <p class='card-text font-italic'><small class='text-muted'>Second Name:&nbsp;</small><small>{{ user.teacher.second_name|title }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Last Name:&nbsp;</small><small>{{ user.teacher.last_name|title }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Age:&nbsp;</small><small>{{ user.teacher.get_teacher_age }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Gender:&nbsp;</small><small>{{ user.teacher.gender|title }}</small></p>
                    <hr>
                    <p class='card-text font-italic' ><small class='text-muted'>Mobile:&nbsp;</small><small>{{ user.teacher.mobile }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Email:&nbsp;</small><small>{{ user.teacher.email }}</small></p>

                    <hr>
                    <p class='card-text font-italic' ><small class='text-muted'>Date Born:&nbsp;</small><small>{{ user.teacher.date_born|title }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Country Born:&nbsp;</small><small>{{ user.teacher.country_born|title }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Nationality:&nbsp;</small><small>{{ user.teacher.nationality|title }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Passport Number:&nbsp;</small><small>{{ user.teacher.passport_number }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Address:&nbsp;</small><small>{{ user.teacher.address|title }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Skills:&nbsp;</small><small>{{ user.teacher.skills|title }}</small></p>
                    <hr>
                    <p class='card-text font-italic' ><small class='text-muted'>Add at:&nbsp;</small><small>{{user.teacher.created_at }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Add by:&nbsp;</small><small>{{ user.teacher.created_by }}</small></p>
                    <br>
                    <p class='card-text font-italic' ><small class='text-muted'>Last Login:&nbsp;</small><small>{{ request.user.last_login }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Last Update at:&nbsp;</small><small>{{ user.teacher.updated_at }}</small></p>
                    <p class='card-text font-italic' ><small class='text-muted'>Last Update by:&nbsp;</small><small>{{ user.teacher.updated_by }}</small></p>
                </blockquote>
            </div>
        </div>
    </div> 

    <div class='row'>   
        <div class="col-sm-12 col-md-4  mb-5">
            <div class="card card-box">
                <div class="card-header">
                    Grade
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                       <ul>
                            {% for grade in user.teacher.grades.all %}
                                <li>
                                    <a href="{%  url 'listings:grade_detail'  grade_slug=grade.slug  %}">
                                            {{ grade.name }}
                                    </a>
                                    <a href="{% url 'listings:grade_attendanc_create' grade_slug=grade.slug %}">
                                        add attendace
                                    </a>
                                </li>
                            {%empty %}
                                <li>Sorry, no grade in {{ user.teacher.grade.name }}.</li>
                            {% endfor %}  
                        </ul> 
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4  mb-5">
            <div class="card card-box">
                <div class="card-header">
                Subjects
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <ul>
                            {% for subject in user.teacher.subjects.all %}
                                <li><a href="{%  url 'listings:subject_detail'  subject_slug=subject.slug  %}">{{ subject.get_subject_full_title }}</a></li>
                            {%empty %}
                                <li>Sorry, no subject in {{ user.teacher.subjec.get_subject_full_title }}.</li>
                            {% endfor %}  
                        </ul> 
                    </blockquote>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4 mb-30">
            <div class="card card-box">
                <div class="card-header">
                    Salary
                </div>
                <div class="card-body">
                    <blockquote class="blockquote mb-0">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>
                    </blockquote>
                </div>
            </div>
        </div>
    </div>


 
</div>



{% endblock content %}